
name: msdcc_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1
  - pytorch-cuda=12.1
  - pytorch-lightning>=2.2
  - pywavelets
  - einops
  - numpy
  - tqdm
  - pip
